#!/bin/bash

if [ -n "$1" ] && [ "$1" != "kernel" ] ; then
    echo "usage: $0 [kernel]";
    exit 1;
fi

if [ ! -d ~/.vim ] ; then
    exit 1;
fi

ignore="-I __THROW -I __attribute_pure__ -I __nonnull -I __attribute__"

comm_dir="/usr/include/linux/*"
# /usr/include/bits/
user_dir="/usr/include/* /usr/include/sys/*"
kern_dir="/usr/src/linux-headers-$(uname -r)/include/linux/*"
kern_dir="${kern_dir} /usr/src/linux-headers-$(uname -r)/include/asm-generic/*"
thrd_dir="/usr/include/netinet/* /usr/include/arpa/*"

if [ "$1" == "kernel" ] ; then
    dir="${kern_dir}";
else
    dir="${comm_dir} ${user_dir} ${thrd_dir}";
fi

argv="--file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes"
argv="${argv} --c-kinds=+p --c++-kinds=+p --fields=+iaS --extra=+q"
tags=~/.vim/systags

ctags ${ignore} ${argv} -f ${tags} ${dir}

grep "${tags}" ~/.vimrc

if [ $? -ne 0 ] ; then
    printf "\n\nset tags+=%s\n" ${tags} >> ~/.vimrc
fi

#"printf '\n\n"ctags"
#""----------------"
#"set tags+=${tags}
#""----------------"' >> ~/.vimrc
